package Interfaces;

import Clases.Evaluador;
import Clases.Node;
import Clases.Producto;
import Clases.Stack;
import static Interfaces.Opcion_Admin.Delete;
import static Interfaces.Iniciar_Sesion.eva;
import static Interfaces.Iniciar_Sesion.colPro;
import javax.swing.JOptionPane;
import static Interfaces.Iniciar_Sesion.AllProduc;
import static Interfaces.Iniciar_Sesion.Aprovados;
import static Interfaces.Iniciar_Sesion.NoAprov;

/**
 *
 * @author Gustavo Adolfo Velasquez Granada Owen Andrés Holguin Molina Yely
 * Leana Gómez Vargas
 */
public class Opcion_Colaborador extends javax.swing.JFrame {

    /**
     * Creates new form Opcion_Admin
     */
    public Opcion_Colaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegiColab = new javax.swing.JButton();
        RegiPro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EliminarPro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        EliminarEva = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegiColab.setText("Registrar colaborador");
        RegiColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegiColabActionPerformed(evt);
            }
        });
        jPanel1.add(RegiColab, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        RegiPro.setText("Registrar Productividad");
        RegiPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegiProActionPerformed(evt);
            }
        });
        jPanel1.add(RegiPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("¿Que desea hacer?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        EliminarPro.setText("Elimanar Productividad");
        EliminarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Eliminar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Registrar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, -1, 20));

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        EliminarEva.setText("Elimanar Evaluador");
        EliminarEva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEvaActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarEva, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Fondo.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegiColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegiColabActionPerformed
        Registrar_Colaborador ventanaColab = new Registrar_Colaborador();
        ventanaColab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegiColabActionPerformed

    private void RegiProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegiProActionPerformed
        Registrar_Productividad ventanaPro = new Registrar_Productividad();
        ventanaPro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegiProActionPerformed

    private void EliminarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProActionPerformed
        String delete = JOptionPane.showInputDialog("Ingrese el código del producto a eliminar");
        Delete(colPro, delete);
        AllProduc.Delete(delete);
        Aprovados.Delete(delete);
        NoAprov.Delete(delete);
        eva.EliminarPro(eva, delete);
    }//GEN-LAST:event_EliminarProActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Iniciar_Sesion ventanaIni = new Iniciar_Sesion();
        ventanaIni.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    private void EliminarEvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEvaActionPerformed
        String delete = JOptionPane.showInputDialog("Ingrese la identificación del evaluador a eliminar");
        Stack aux = eva.SearchEva(delete);

        if (eva.DeleteEva(delete)) {
            Node auxA = eva.getFirst();
            Producto p;
            while (!aux.isEmpty()) {
                p = (Producto) aux.Pop();
                colPro.Enqueque(p);
            }

            AsignarEva();
        } else {
            JOptionPane.showMessageDialog(null, "El evaluador no se encuentra en la lista");
        }
    }//GEN-LAST:event_EliminarEvaActionPerformed

     public void AsignarEva() {
        Node aux = eva.getFirst();
        while (!colPro.isEmpty()) {
            Producto prod = (Producto) colPro.Dequeque();
            ((Evaluador) aux.getData()).getProductos().Push(prod);
            aux = aux.getLink();
            if (aux == null) {
                aux = eva.getFirst();
            }
        }
        JOptionPane.showMessageDialog(null, "Evaluadores Asignados");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcion_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcion_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcion_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcion_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opcion_Colaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarEva;
    private javax.swing.JButton EliminarPro;
    private javax.swing.JButton RegiColab;
    private javax.swing.JButton RegiPro;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
