package Interfaces;


import Clases.Colaborador;
import static Interfaces.Iniciar_Sesion.UsuarioIni;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Adolfo Velasquez Granada
 *                 Owen Andrés Holguin Molina
 *                 Yely Leana Gómez Vargas
 */
public class Registrar_Colaborador extends javax.swing.JFrame {

    //se crea la lista usuario y el colaborador
    //static List usuario = new List();
    static Registrar_Colaborador rc;
    static Colaborador Adolfo;

    public static Registrar_Colaborador getRc() {
        return rc;
    }

    

    public Registrar_Colaborador() {
        initComponents();
//        usuario = ar.LeerLColabolador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RegistrarColab = new javax.swing.JButton();
        NombreColb = new javax.swing.JTextField();
        IdColab = new javax.swing.JTextField();
        RolColab = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 100, -1, -1));

        jLabel2.setText("Contraseña(ID)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 131, -1, -1));

        jLabel3.setText("Rol");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 162, -1, -1));

        RegistrarColab.setText("Registrar");
        RegistrarColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarColabActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarColab, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 209, -1, -1));

        NombreColb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColbActionPerformed(evt);
            }
        });
        jPanel1.add(NombreColb, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 97, 159, -1));
        jPanel1.add(IdColab, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 128, 159, -1));

        RolColab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Docente Carrera", "Docente Ocasional", "Docente Catedra", "Administrativo", "Estudiante" }));
        RolColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolColabActionPerformed(evt);
            }
        });
        jPanel1.add(RolColab, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 159, 159, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Registrar Colaborador");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 39, -1, -1));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 209, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Fondo.jpeg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 420, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarColabActionPerformed
       //se añade el colaborador a la lista
        String nombre = NombreColb.getText();
        String id = IdColab.getText();
        String rol = (String) RolColab.getSelectedItem();
        Adolfo = new Colaborador(id, nombre, rol);
        (Interfaces.Iniciar_Sesion.getIni().usuario).AddFirst(Adolfo);
        JOptionPane.showMessageDialog(null, "El colaborador ha sido registrado exitosamente");

        NombreColb.setText("");
        IdColab.setText("");
    }//GEN-LAST:event_RegistrarColabActionPerformed

    private void RolColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolColabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RolColabActionPerformed

    private void NombreColbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColbActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        
    }//GEN-LAST:event_formWindowClosing

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
          if(UsuarioIni.getSelectedItem().equals("Administrador")){
            Opcion_Admin ob = new Opcion_Admin();
            ob.setVisible(true);
            this.setVisible(false);
        }else{
          Iniciar_Sesion ini = new Iniciar_Sesion();
        ini.setVisible(true);
        this.setVisible(false);  
        }
          (Interfaces.Iniciar_Sesion.ini.ar).EscribirLColabolador((Interfaces.Iniciar_Sesion.ini.usuario));
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_Colaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                rc=new Registrar_Colaborador();
                rc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdColab;
    private javax.swing.JTextField NombreColb;
    private javax.swing.JButton RegistrarColab;
    private javax.swing.JComboBox RolColab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
